### ISSUE TITLE
NSG GeoPackage File Names

### ISSUE THREAD

**Issue by royrathbun** [ngageoint/geopackage-nsg-profile#1]
In the original draft of the NSG GeoPackage Profile, Section 6.1, File Names, recommended naming conventions were omitted.  We need input from the community to provide those recommendations.  Those will be discussed here, and added to the next iteration of the document.

**Comment by pdaisey** [comment]
Need some sample organization-specific (NGA, DoD Services) pattern examples, e.g.
{producer}_{data product (acronym)}_{geo area coverage (acronym)}_{scale(s)}_{version}_{date}
The actual patterns are not specified in the profile, but every data producer should follow a pattern 
that informs data users and that they become familiar with.  The point is to avoid totally ad-hoc names like "Freds_Monday_Tiles".gpkg.  It would be best if current data producers can be motivated to provided their preferred file name patterns.

**Comment by MicahBrachman** [comment]
Here is one idea we've come up with at AGC, which is based on the GENC Geopolitical Entity character codes and MGRS grid coordinates:

(2-character code)(3-character subdivision code)(MGRS coordinate 1km precision)(maximum zoom level)

An NSG GeoPackage covering an AOI in Kabul to zoom level 20 would have the following file name:

AFKAB42SWD0817z20.gpkg

**Comment by royrathbun** [comment]
Paragraph edited; suggestion added.  See Issue #13, which has draft Corrigendum embedded.
