### ISSUE TITLE
Section 8.5 Tile Matrix Extent

### ISSUE THREAD

**Issue by KRyden** [ngageoint/geopackage-nsg-profile#10]
The Tile Matrix Extent capability is an application requirement, not a GeoPackage profile item.  This need to be moved to a separate document and pulled out of the NSG profile.

Actions:
1) Delete section 8.5 Tile Matrix Extent from the NSG Profile
2) Delete reference to section 8.5 in the first paragraph of section 6.2 Extensions
3) Define a new document type for NSG Application Extensions on Geopackage (or perhaps more generally Simple Features which includes GeoPackage) in which the Tile Matrix Extent application requirement can reside.

Discussion item - it may be possible to meet the requirements of the Tile Matrix Extent item by adding the "extent_type" property to the core GeoPackage tile tables - the information is generally known at the time the tiles are written.  This would need to be discussed in the GeoPackage SWG, but such an update if adopted would eliminate the need for this application extension.

**Comment by royrathbun** [comment]
1. Section 8.5 deleted; table references too.
2. Done.
3. Transferred to separate issue.
