### ISSUE TITLE
Section 3 - References

### ISSUE THREAD

**Issue by KRyden** [ngageoint/geopackage-nsg-profile#5]
Table 2: Normative references in the NSG GeoPackage Interoperability Standard

The reference to OGC 01-009 should be dropped.  We're using the new coordinate reference spec which supersedes this document, and this document has been the source of non-interoperable (and incorrect) CRSs in sample GeoPackages.

Should also include ISO 19125:1 and 19125:2 Simple Features to the reference specifications.  This is the harmonized ISO specification that parallels the OGC Simple Feature Specification

Actions: Drop reference to OGC 01-009, add references to ISO 19125:1 and 19125:2

**Comment by royrathbun** [comment]
Made suggested corrections.
