### ISSUE TITLE
Section 8.3 Tile Pyramid Design

### ISSUE THREAD

**Issue by KRyden** [ngageoint/geopackage-nsg-profile#8]
Last paragraph in the section - starts with "These features ultimately server to simplify..."

This paragraph contains editorial comments on the validity of the web Mercator projection and comments on perceived simplicity of changing in commercial products and for commercial use. The document has already made the point of not using web Mercator, and provided reference to NGA guidance - further editorial comments are not needed, and should be removed.

Action: rewrite paragraph to remove unnecessary editorial comments

**Comment by royrathbun** [comment]
Removed para.  Added "....  Maintaining a tile-scheme identical to EPSG::3857 will simplify the switch to WGS 84 / Tiled Mercator.  Only the conversion formulas between Lon./Lat. and Mercator (x, y) will need to be modified; (x, y) to (Px, Py) conversion is retained" to last two lines of previous paragraph.

**Comment by royrathbun** [comment]
Close issue
