### ISSUE TITLE
Section 7.3 - Data Validity Constraints

### ISSUE THREAD

**Issue by KRyden** [ngageoint/geopackage-nsg-profile#9]
Table 32 Data Validity Constraints

Validity constraints table ID#8 "gpkg_geometry_columns" - 

The data validity checks on page 49 (id#8) still seems to allow the curve types and even more extended types. They are, however, forbidden on page 62 which is the desired state.

Document table references are probably incorrect - should be  45 and 46, not 42 and 43; 42 and 43 were from an older document.  

Action: This was missed when updates to remove curve and extended geometries was made - need to complete the updates by correcting and clarifying the constraints in the table.

**Comment by pdaisey** [comment]
Correct document table references
Change "One of geometry type names " to
"One of the linear (per Req 40 below) geometry type names "

**Comment by royrathbun** [comment]
Fixed.
